# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mosquito_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mosquito_app_db
    ports:
      - "5495:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: mosquito_server
    ports:
      - "3001:3001"
    volumes:
      - ./packages/server/src:/app/src
    depends_on:
      - db
    # environmentの代わりにenv_fileを使用
    env_file:
      - ./packages/server/.env 

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: mosquito_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend/src:/app/src
    depends_on:
      - server

volumes:
  postgres_data: